version: '2'
services:
  wordpress:
    scale: 2
    start_on_create: true
  wp-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: wordpress
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  db:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3306
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 120000
